# Generated by Django 4.0 on 2021-12-08 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('about', models.TextField(blank=True, max_length=500, null=True, verbose_name='О себе')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='День рождения')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='user/avatar', verbose_name='Фотография')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='auth.user', verbose_name='Пользователь')),
            ],
        ),
    ]
