# Generated by Django 4.0 on 2021-12-23 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['user', 'name'], 'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
    ]
