# Generated by Django 4.0 on 2022-01-19 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='auth.user', verbose_name='Адресат')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='senders', to='auth.user', verbose_name='Адресант')),
            ],
            options={
                'verbose_name': 'Подписчик',
                'verbose_name_plural': 'подписчики',
            },
        ),
    ]
