# Generated by Django 4.0 on 2022-01-05 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postreaction',
            name='object_id',
            field=models.IntegerField(db_index=True, verbose_name='pk объекта'),
        ),
    ]
