# Generated by Django 4.0 on 2021-12-23 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profile_options'),
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.profile', verbose_name='Автор'),
        ),
    ]
